#! /usr/bin/env fish

# Prints a random fish name and description
# Usage:
#   source fish.fish
#   fishfish
# Use `--no-greet` to supress the greeting graphics

# The fish list is sourced from Wikipedia
# So all fish names are real
# Descriptions are generated by LLM and may be nonsensical or inaccurate

set fish_list "\
African glass catfish | Nearly transparent freshwater fish native to African rivers, known for their delicate appearance and schooling behavior.
African lungfish | Primitive air-breathing freshwater fish from Africa, famous for surviving dry seasons by burrowing into mud.
Aholehole | Hawaiian flagtail found along Pacific coasts; silvery, resilient fish important in local cuisine.
Airbreathing catfish | Adaptable catfish species with specialized respiratory organs that allow them to survive out of water for short periods.
Airsac catfish | Unique catfish that breathe using internal air sacs; well adapted to oxygen-poor environments.
Alaska blackfish | Hardy, cold-water fish from Alaska with ability to endure freezing conditions and low oxygen.
Albacore | Highly migratory oceanic tuna, valued for its mild, fatty meat and use in gourmet cuisine.
Alewife | Small herring species found in North America, crucial to lake ecosystems and fisheries.
Alfonsino | Bright red, deep-sea fish often found near underwater mountains; valued for its culinary qualities.
Algae eater | Group of fish that feed primarily on algae and help maintain clean aquatic ecosystems in home aquariums.
Alligatorfish | Spiny, armored bottom-dweller of cold northern seas, with a lizard-like appearance.
Alligator gar | Massive, predatory freshwater fish of North America, recognized by its elongated jaws filled with sharp teeth.
Amberjack | Powerful, swift ocean predators, prized by sport fishers for their fighting ability and taste.
American sole | Flattened bottom-dwelling fish from American waters, camouflaged and adapted to sandy or muddy substrates.
Amur pike | Aggressive pike species native to rivers in East Asia; popular with anglers for its size and striking pattern.
Anchovy | Tiny, schooling fish, prominent for its strong-flavored presence in global culinary dishes and its role in the food web.
Anemonefish | Vibrant coral reef fish, famous for living symbiotically among sea anemone tentacles; includes ‘Nemo’.
Angelfish | Strikingly shaped ornamental fish, found in both freshwater and marine aquariums; known for their vivid colors and graceful movement.
Lophius piscatorius|Angler | Deep-sea ambush predator with a luminescent lure on its head to attract prey.
Angler catfish | Catfish species with whiskers resembling fishing lures, aiding their predatory lifestyle.
Anglerfish | Notorious deep-sea creature distinguished by a glowing lure and jagged teeth; among the ocean’s strangest hunters.
Antarctic cod | Robust, cold-tolerant fish from the waters of Antarctica, key to the region’s food chain.
Antarctic icefish | Extraordinary Antarctic species with antifreeze proteins and clear blood, adapted to subzero marine environments.
Antenna codlet | Tiny deep-sea fish sporting elongated sensory extensions; little is known about its biology.
Arapaima | One of the world’s largest freshwater fish, native to the Amazon; breathes air, and is essential in local cultures.
Archerfish | Famous for precise jets of water used to knock insects into the river; found in mangroves and estuaries of Southeast Asia.
Arctic char | Salmonid fish thriving in northern cold lakes and rivers; highly valued for its delicate flesh.
Armored gurnard | Bottom-dwelling fish covered in thick bony plates, often found in European coastal waters.
Armored searobin | Spiny fish with wing-like pectoral fins and armor plating; inhabits sandy sea floors.
Armorhead | Rugged deep-sea fish with a prominent bony shield on its head; frequent in oceanic trenches.
Armorhead catfish | Catfish species adapted with a thick skull, offering protection in rough habitats.
Armoured catfish | South American catfish with interlocking bony plates, commonly used as algae eaters in aquariums.
Arowana | Sleek, predatory freshwater fish often called “dragon fish”; revered in Asia for its perceived luck.
Arrowtooth eel | Sinister-looking deep-sea eel with needle-sharp teeth and an elongated body.
Asian carp | Highly invasive freshwater fish from Asia causing ecological challenges in non-native environments.
Asiatic glassfish | Transparent freshwater fish from Asia, popular in aquariums for their visible internal organs.
Atka mackerel | North Pacific species recognized by its bold stripes; important in commercial fisheries.
Atlantic bonito | Fast-moving schooling fish, valued for sport and cuisine; cousin to the tuna.
Atlantic cod | Iconic commercial fish, foundation of North Atlantic fisheries for centuries; mild white flesh.
Atlantic herring | Essential schooling fish, cornerstone for ecosystems and human consumption in the North Atlantic.
Atlantic salmon | Migratory fish revered for its rich meat and athletic upstream journeys; staple in aquaculture.
Atlantic saury | Slender, silvery ocean fish notable for its speedy movements and importance in East Asian diets.
Atlantic sharpnose shark | Small, energetic coastal shark found in Atlantic waters; known for its pointed snout.
Atlantic silverside | Tiny, glimmering fish common along the Atlantic coast; vital food for larger species.
Australasian salmon | Swift salmonid inhabiting Australian and New Zealand coasts; popular among recreational anglers.
Australian grayling | Endangered freshwater fish native to southeastern Australia, with a silvery sheen and delicate features.
Australian herring | Coastal fish from southern Australia; valued for its taste and role in fisheries.
Australian lungfish | Ancient, air-breathing species found only in Queensland rivers; evolutionary link between fish and amphibians.
Australian prowfish | Unique, cryptic reef-fish found solely in Australian waters; recognized by its odd profile.
Ayu sweetfish|Ayu | Delicate Japanese river fish cherished for its sweet flavor; centerpiece of local culinary traditions.
Baikal oilfish | Deep-dwelling fish from Lake Baikal, Russia; oily flesh and elusive habits.
Bala shark | Sleek, silvery favorite in aquariums; not a true shark, but known for its graceful swimming and schooling.
Ballan wrasse | Large, colorful wrasse of European rocky reefs; a keystone species known for its tough jaws.
Bamboo shark | Small, nocturnal shark with banded patterns, often inhabiting coral reefs and sandy bottoms.
Banded killifish | Attractive freshwater fish marked by horizontal bands; common in North American lakes.
Bandfish | Ribbon-like marine fish that swim vertically; little known about their deep-sea lifestyle.
Bangus | Milkfish central to Asian aquaculture and cuisine, appreciated for its mild flavor and versatility.
Banjo fish|Banjo | Flattened, banjo-shaped fish from South America; adept at camouflaging under mud.
Banjo catfish | Small, bottom-dwelling catfish native to South American rivers, resembling a banjo in shape.
Barbus|Barb | Diverse group of small cyprinids with bristly barbels; popular in aquariums and rivers alike.
Barbus barbus|Barbel | European river fish notable for sensory barbels around the mouth; sought after by anglers.
Barbeled dragonfish | Deep-sea predator sporting chin barbels and photophores for attracting prey in total darkness.
Barbeled houndshark | Lesser-known shark distinguished by fleshy barbels under its mouth; found in Asian seas.
Barbel-less catfish | Catfish species evolved without the signature whisker-like barbels; typically found in specialized habitats.
Barfish | Regional term for yellow perch, a vibrant sunfish beloved by North American anglers.
Barracuda | Sleek, powerful ocean predator renowned for aggressive attacks and razor-sharp teeth.
Barracudina | Slender deep-sea fish, distantly related to barracuda; adapted for swift swimming at depth.
Barramundi | Premier Australian freshwater fish, highly prized for its size, taste, and adaptability.
Barred danio | Small, horizontally-striped freshwater fish, social and active in aquariums.
Barreleye | Mysterious deep-sea fish with a transparent domed head and upward-facing tubular eyes.
Basking shark | Enormous, slow-moving shark that filters tons of plankton; second largest fish species globally.
Bass | Diverse group of strong game and food fish with distinctive spiny dorsal fins; vital to fisheries.
Basslet | Tiny, brilliantly colored reef fish that add vibrancy and personality to tropical aquariums.
Bat ray | Large ray with distinctive bat-shaped wings, found in coastal habitats and noted for leaping ability.
Batfish | Peculiar, bottom-dwelling fish with flattened bodies and odd swimming styles; found in tropical seas.
Beachsalmon | Coastal fish frequently seen darting in waves near beaches; fast swimmers and popular with local fishers.
Beaked salmon | Deep-sea fish named for its elongated snout, adapted for swift movements in dark waters.
Beaked sandfish | Sand-dwelling fish with a pointed beak, specialized for hunting small organisms on the seafloor.
Beardfish | Deep-sea species with distinctive chin barbels, used to sense food in the ocean depths.
Beluga sturgeon | Giant sturgeon from Eurasian rivers; famed for caviar production and conservation importance.
Bengal danio | Vibrant, small freshwater fish native to Bengal; prized for their energy and coloration.
Betta | Iconic “Siamese fighting fish” with stunning colors, dramatic fins, and fierce territorial instincts.
Bichir | Primitive, heavily-armored freshwater fish; capable of breathing air and walking short distances on land.
Bicolor goat fish | Striking reef fish with two-tone coloration and sensitive chin barbels.
Bigeye | Deep-water fish with oversized eyes for vision in darkness; several related species worldwide.
Bigeye squaretail | Unique deep-sea fish with large eyes and a square-shaped caudal fin.
Bighead carp | Robust, filter-feeding carp native to Asia; crucial in aquaculture but invasive elsewhere.
Bigmouth buffalo | Large native North American fish with prominent mouth; targeted in sport and commercial fishing.
Bigscale | Group of fish with noticeably large, protective scales; can refer to several species.
Bigscale pomfret | Deep-sea pomfret species recognized by oversized scales along its body.
Istiophoridae|Billfish | Lightning-fast oceanic predators; includes marlin and sailfish, defined by elongated bills.
Bitterling | Tiny European and Asian cyprinid, noted for its mating with freshwater mussels.
Black angelfish | Popular aquarium angelfish with dramatic black coloration and elegant fins.
Black bass | North American sport fish, including largemouth and smallmouth bass; feisty and highly adaptable.
Black dragonfish | Otherworldly deep-sea fish with glowing photophores and immense fangs; master of darkness.
Black mackerel | Fast, dark-scaled ocean fish found in tropical/warm seas; streamlined for pursuit.
Black neon tetra | Striking aquarium fish with black-and-neon stripes; peaceful and great for community tanks.
Black scabbardfish | Sword-shaped deep-sea predator, sought after for its delicate, white meat.
Black scalyfin | Jet-black reef inhabitant found around Australia, notable for territorial behavior.
Black sea bass | Versatile North American fish, a favorite for both sport and cuisine; recognized by dusky coloration.
Black swallower | Deep-sea oddity known for ingesting prey up to twice its own size thanks to a stretchy stomach.
Black tetra | Hardy, small black aquarium fish with subtle silver highlights and active schooling habits.
Black triggerfish | Athletic reef fish with dark hues and a distinctive trigger spine used for defense.
Blackchin | Subtle, dark-patched fish found in both freshwater and marine environments; varied species.
Blackfin tuna | Swift, small oceanic tuna of tropical waters, valued for sport and sushi.
Blackfish | Catch-all name for several darkly colored freshwater and marine species.
Blacktip reef shark | Agile tropical shark instantly recognized for its black-edged fins patrolling coral reefs.
Bleak | Slender, silvery European freshwater fish; plays a role in the food chain and recreational fishing.
Blenny | Small, elongated reef fish famed for quirky behavior and fascinating adaptations.
Blind goby | Eyeless cave-dwelling goby, evolved to live in perpetual darkness; rarely seen.
Blind shark | Shark with reduced eyesight, relying on keen senses of smell and movement in murky waters.
Blobfish | Deep-sea marvel known for its gelatinous, droopy appearance outside its natural high-pressure habitat.
Blowfish | Inflatable fish famous for their ability to puff up as a defense mechanism; some species are highly toxic.
Blue catfish | Large, hardy North American catfish with bluish tint; popular for angling and cuisine.
Blue danio | Tiny, iridescent blue aquarium fish, lively and easy to care for.
Trevalla|Blue eye trevalla | Deep-sea predator with hypnotic blue eyes; sought after by gourmet chefs.
Blue shark | Elegant, slender ocean shark known for its brilliant blue coloration and migratory habits.
Blue triggerfish | Dazzling reef fish exhibiting shades of blue and active defensive behavior.
Blue whiting | Northern Atlantic commercial fish, common in the food industry for mild taste.
Blue-redstripe danio | Small, vividly striped freshwater aquarium fish; energetic and easy to breed.
Bluefin tuna | Famous for sheer size, strength, and rich flavor; sought in sushi and luxury seafood markets.
Bluefish | Voracious, swift coastal predator with razor teeth, famed among sport fishers.
Bluegill | Popular, resilient North American sunfish, a staple for fishing beginners and pond stocking.
Blue gourami | Pleasant, shimmering aquarium fish, noted for labyrinth breathing organs.
Bluntnose knifefish | Streamlined freshwater fish with a rounded snout and electric sensing abilities.
Bluntnose minnow | Small, robust minnow with distinctive blunt snout; vital in river and lake food webs.
Boafish | Eel-like, deep-sea fish with serpentine movements; little is known of its habits.
Boarfish | Deep-bodied, reddish marine fish with large eyes and compressed form.
Bobtail snipe eel | Unusual deep-ocean eel with a compact tail, adapted for life at great depths.
Bocaccio rockfish|Bocaccio | Large Pacific rockfish, endangered due to overfishing; recognized by protruding lower jaw.
Boga | Schooling fish of the Atlantic, energetic and integral to local fisheries.
Bombay duck | Slender, lizardfish from Indian waters; beloved in regional cuisine for its pungent aroma.
Bonefish | Fast, silvery game fish adored by saltwater fly fishers for its elusive nature.
Bonito | Speedy, schooling oceanic fish related to tuna; mild, flavorful meat common in global dishes.
Bonnethead shark | Small hammerhead shark with a unique shovel head; found in shallow coastal waters.
Bonnetmouth | Small, tropical reef fish named for its characteristic upturned mouth.
Bonytail | Endangered North American freshwater species, critical for conservation efforts.
Osteoglossoidei|Bonytongue | Ancient family of surface-dwelling fish with distinctive bony mouth plates.
Bowfin | Ancient, air-breathing freshwater fish native to North America; called ‘living fossil’.
Boxfish | Cube-like reef fish with tough, armored skin; some release toxins when stressed.
Bramble shark | Rare deep-sea shark covered with thorny denticles; found in Atlantic and Pacific depths.
Bream | Collective name for several freshwater and marine species with laterally compressed bodies.
Brill | Flatfish native to European waters, prized for delicate, fine-textured meat.
Bristlemouth | Abundant deep-sea species recognizable by its luminous bristle-lined mouth.
Bristlenose catfish | Small, gentle catfish popular in aquariums for natural algae control.
Broadband dogfish | Small, deep-sea shark with characteristic wide markings along its body.
Bronze corydoras | Jeff bronze-colored catfish frequently kept in aquariums; peaceful and hardy.
Brook lamprey | Jawless, parasitic freshwater fish resembling ancient vertebrates.
Brook stickleback | Spiny, small inhabitant of North American streams; agile and well camouflaged.
Brook trout | Vibrant jewel of North American rivers; favorite among fly fishers for its colorful markings.
Brotula | Deep-sea, eel-like fish with elongated bodies and secretive behavior.
Brown trout | Highly adaptable game fish found worldwide, celebrated for challenging anglers and nuanced coloration.
Buffalo fish | Robust North American freshwater fish; significant for commercial and recreational fishing.
Bull shark | Powerful, aggressive shark able to thrive in both fresh and salt water environments.
Bull trout | North American salmonid favoring cold, clear rivers; prized by conservationists and sport fishers.
Bullhead | Small, bottom-dwelling freshwater fish with broad heads and spiny fins.
Bullhead shark | Small, blunt-nosed shark found in shallow waters; known for armored appearance.
Bumblebee goby | Miniature, brightly striped aquarium fish resembling a bumblebee.
Burbot | Northern freshwater fish with cod-like features; uniquely adapted to cold, icy waters.
Japanese amberjack|Buri | Culinary staple of Japan, this powerful fish is central to sushi cuisine.
Burma danio | Small, lively freshwater aquarium fish from Myanmar with shimmering scales.
Burrowing goby | Goby that digs burrows in sandy habitats, exhibiting symbiotic behavior with shrimp.
Pentapodus nagasakiensis|Butterfish | Delicate, buttery-textured fish enjoyed in Asian cuisine; found in shallow reefs.
Butterfly ray | Graceful ray with wing-like fins; glides elegantly in tropical and subtropical seas.
Butterflyfish | Iconic reef dwellers with disc-shaped bodies and dazzling patterns, a favorite of snorkelers.
California flyingfish | Aerodynamic fish that soars above Pacific waves; famous for long glides to escape predators.
California halibut | Large, sought-after flatfish found on the US west coast; highly valued for its tender flesh.
Canary rockfish | Vivid yellow rockfish native to the Pacific; significantly impacted by conservation measures.
Candiru | Infamous Amazonian parasitic catfish, known for entering gill cavities of larger fish and occasionally mammals.
Candlefish | Tiny, oily Pacific fish historically used as candles due to its fat content.
Capelin | Torpedo-shaped schooling fish from cold seas, important in marine food chains and human diets.
Cardinal tetra | Dazzlingly colored aquarium fish with glowing red and blue stripes; thrives in peaceful community tanks.
Cardinalfish | Small, often nocturnal reef fish, recognized for red hues and paternal mouthbrooding.
Carp | Large, adaptable freshwater fish found worldwide; central to aquaculture and angling.
Carpetshark | Small, cryptically patterned sharks superbly camouflaged against ocean floors.
Carpsucker | North American freshwater fish with puckered mouth adapted for feeding on bottom detritus.
Scyliorhinidae|Cat shark | Small, spotted sharks populating temperate and tropical seas; notably diverse.
Catalufa | Eye-catching, vividly colored reef fish; popular for its nocturnal habits and bright appearance.
Catfish | Highly diverse group, famous for whisker-like barbels and strong adaptability to varied waters.
Catla | Large, important Indian freshwater fish in regional aquaculture, notable for its rapid growth.
Cavefish | Fish evolved for perpetual darkness in caves; often blind and translucent.
Celebes rainbowfish | Colorful, lively fish from Sulawesi, prized in home aquaria.
Central mudminnow | Small, resilient North American fish adapted for muddy, oxygen-poor environments.
Chain pickerel | Predatory freshwater fish with striking chain-like markings and rapid strike speed.
Channel bass | Also called red drum, famous for energetic fights and highly valued as a game fish.
Channel catfish | Common North American catfish, a staple in aquaculture, fishing, and cuisine.
Salvelinus|Char | Cold-loving salmonids found in northern rivers and lakes; popular for sport and eating.
Cherry salmon | Brightly colored salmon species of East Asia; revered in fishing and culinary traditions.
Chimera | Deep-sea fish with cartilaginous skeletons; sometimes called ‘ghost sharks’ for faint appearance.
Chinook salmon | Largest Pacific salmon species, iconic for grand migrations and economic importance.
Cherubfish | Tiny, vibrantly colored reef angelfish, prized in nano reef tanks.
Chub | Broad name for several robust freshwater species found in rivers and streams.
Chubsucker | Native North American fish with a sucker-shaped mouth for feeding on detritus.
Chum salmon | Widespread Pacific salmon, crucial to ecological cycles and the fishing industry.
Cichlid | Exceptionally diverse family, with dramatic colors and surprising behaviors; backbone of the aquarium world.
Cisco | Silvery, small freshwater fish vital to northern lake ecosystems and commercial fisheries.
Climbing catfish | Remarkable catfish able to climb rocks and move between water bodies; found in southern Asia.
Climbing gourami | Ornamental fish able to breathe air, sometimes overland travelers when water is scarce.
Climbing perch | Hardy fish famed for overland journeys between ponds using a specialized labyrinth organ.
Clingfish | Tiny coastal fish with suction discs specialized for adhering to surfaces in turbulent waters.
Clown loach | Playful, bright orange aquarium favorite from Southeast Asia; best kept in groups.
Clown triggerfish | Spectacular, spotted reef fish with bold patterns and a distinctive trigger spine.
Clownfish | Renowned, symbiotic reef dwellers, immortalized by “Finding Nemo”; live safely among anemone tentacles.
Cobbler | General term for bottom-dwelling fish, often with a mottled appearance; includes several species.
Cobia | Streamlined, fast-growing ocean predator; a rising star in aquaculture and sport fishing.
Cod | Broad name for several key commercial fish species, foundations of northern culinary and fishing heritage.
Codlet | Small, deep-sea cod relatives; infrequently encountered, adapted for life in darkness.
Codling | Juvenile or small species related to cod, present in both commercial and natural contexts.
Coelacanth | Legendary “living fossil”, once thought extinct; deep-sea fish with ancient, lobed fins.
Coffinfish | Deep-sea dweller capable of inflating into a boxy shape; fascinating adaptation for survival.
Coho salmon | Vital Pacific salmon known for their striking red coloration during spawning and athletic leaps.
Coley | Alternative name for pollock, essential in processed seafood markets in Europe.
Collared carpetshark | Small, well-patterned shark with collar marking; native to Australian and Indonesian reefs.
Collared dogfish | Deep-sea shark with unusual collar-like marking near the gills; little is known about its biology.
Colorado squawfish | Once-abundant, large North American freshwater fish; critically endangered and subject to conservation efforts.
Combfish | Unusual fish with a dorsal fin shaped like a comb; found in tropical and subtropical seas.
Combtail gourami | Aquarium gourami with a comb-shaped tail fin; noted for peaceful behavior and intricate mating.
Combtooth blenny | Comical, reef-dwelling blenny with comb-like teeth suited for scraping algae off rocks.
Common carp | One of the world’s most widespread and adaptable species; valued in aquaculture and recreational fishing.
Common tunny | Historic term for Atlantic bluefin tuna, the largest and most prized of tunas.
Conger eel | Large, muscular marine eel known for fierce defense and pale white flesh used in Asian cuisine.
Convict blenny | Reef fish known for black-and-white stripes and cooperative burrow nesting behavior.
Convict cichlid | Small, pugnacious aquarium fish distinguished by striking jailhouse stripes.
Cookiecutter shark | Small, deep-sea shark famed for circular wounds inflicted on larger animals.
Coolie loach | Playfully striped, diminutive aquarium loach native to Southeast Asian streams.
Cornetfish | Unusually long, slender reef fish with extended snout; masters of stealthy hunting.
Cow shark | Primitive shark characterized by an extra pair of gill slits; found in deep or murky waters.
Cowfish | Boxy reef fish with protruding horn-like structures; bright, often toxic.
Cownose ray | Ray with a distinctive cow-like snout, travels in large schools in coastal waters.
Crappie | Favorite North American panfish, known for their social schooling and delicious white meat.
Creek chub | Robust little fish native to North American streams and rivers; vital forage for larger species.
Crestfish | Rare, deep-sea fish with a spectacularly long dorsal crest; origins shrouded in mystery.
Crevice kelpfish | Slender fish that vanish among cracks and kelp fronds, excellent at camouflage.
Sciaenidae|Croaker | Family of fish producing croaking sounds; important in commercial and sport fishing.
Crocodile icefish | Antarctic species with completely clear blood, offering insights into cold adaptation.
Crocodile shark | Small but fierce deep-sea shark; equipped for rapid bursts of speed and predation.
Crucian carp | Hardy, golden European freshwater fish tolerant of challenging water conditions.
Cuckoo wrasse | Brilliantly colored wrasse from European coasts; changes color and sex as it matures.
Cusk | Deep, cold-dwelling Atlantic fish with a cod-like shape and firm white flesh.
Cusk-eel | Eel-shaped, deep-sea fish found in crevices and sediments worldwide.
Cutlassfish | Dazzling, ribbon-like predatory fish with silvery, blade-shaped bodies.
Cutthroat eel | Deep-sea predator with slit-like throat and a torpedo-shaped body.
Cutthroat trout | North American trout identified by a characteristic red throat slash; thrives in cold streams.
Common dab|Dab | Small European flatfish with delicate flavor and a laterally compressed body.
Dace | Lively, small freshwater cyprinid, important in both wild food chains and angling.
Daggertooth pike conger | Aggressive, eel-like predator with dagger-like fangs, found in Indo-Pacific depths.
Damselfish | Energetic, brilliantly colored reef fish known for territorial defense and nesting.
Danio | Lively, small freshwater aquarium fish; hardy and colorful species for beginners.
Dartfish | Streamlined, darting reef fish, capable of fast movements and striking coloration.
Dealfish | Long, ribbon-like deep-sea fish often found in midwater trawls; little known about their biology.
Death Valley pupfish | Endangered miniature fish adapted to extreme heat and salinity of Death Valley springs.
Deep-sea eel | Catch-all for various elongated fishes thriving in oxygen-poor, dark depths with extraordinary adaptations.
Deep-sea smelt | Silvery, slender fish of the ocean’s abyss; integral to deep-dwelling food chains.
Deepwater cardinalfish | Species of cardinalfish dwelling beyond conventional reefs; often with unique coloring and behavior.
Deepwater flathead | Deep-sea predator with flat skull suited for ambushing prey on the ocean bottom.
Deepwater stingray | Rare, disc-shaped stingray adapted to great ocean depths.
Delta smelt | Small, endangered fish native to California’s delta, central to ecological health and conservation.
Demoiselle | Cheerful, reef-dwelling damselfish, adding movement and bright color to tropical reefs.
Denticle herring | Robust herring with tooth-like scales for enhanced protection in South American waters.
Desert pupfish | Resilient, tiny fish surviving in arid, alkaline springs and streams; flagship conservation species.
Devario | Social, fast-swimming cyprinids from South and Southeast Asia; loved for vibrant stripes.
Devil ray | Imposing, plankton-feeding ray with wing-like fins and a sinister silhouette.
Dhufish | Highly prized Australian food fish, known for large size and delectable meat.
Discus | Elegant, round aquarium fish cherished for radiant colors and complex behavior.
Dogfish | Small sharks with sharp spines and flexible bodies; pillars of temperate coastal ecosystems.
Dogfish shark | Common term for various small sharks, easy to identify by their two dorsal spines.
Dogteeth tetra | Predatory tetra with pronounced fangs, found in South American rivers.
Dojo loach | Hardy, burrowing aquarium loach famed for weather prediction by their lively antics.
Dolly Varden trout | Dazzling, spotted trout native to North America and Asia; prefers cold, clear waters.
Dolphin fish | Also called mahi-mahi; spectacularly colored, acrobatic, and central to tropical pelagic fisheries.
Dorab wolf-herring | Aggressive, elongated fish with prominent canine teeth; found in Indo-Pacific coastal seas.
Dorado | General name for several golden-hued fish, often targeted in sport fishing for their fighting capacity.
List of fishes known as dory|Dory | Deep-bodied group of sea fish prized in European cuisine; includes the famous John Dory.
Dottyback | Small, vibrant reef fish adding bold accents and personality to coral aquaria.
Dragon goby | Eel-like aquarium fish with mud-dwelling habits and a spectacularly elongated body.
Dragonet | Diminutive, stunningly colored reef species renowned for elaborate courtship displays.
Dragonfish | Deep-sea monsters with glowing lures and aggressive predatory tactics.
Driftfish | Open-ocean deep-sea fish often found beneath floating debris; largely unknown to science.
Driftwood catfish | Small, nocturnal catfish hiding in sunken logs and debris in South American rivers.
Drum | Family of fish noted for drumming sounds; includes important commercial and sport species worldwide.
Percophidae|Duckbill | Duck-billed marine fish with unique mouth structure for bottom feeding.
Duckbill eel | Eel with beak-like mouth, adapted for snatching prey from soft sediment.
Dusky grouper | Imposing reef fish with dusky scales, revered among Mediterranean divers and fishers.
Dusky shark | Medium-sized shark with somber coloration inhabiting temperate and tropical oceans globally.
Dwarf gourami | Compact, colorful aquarium gourami celebrated for its peaceful nature and ease of care.
Dwarf loach | Tiny, sociable freshwater loach, ideal for nano aquariums and gentle communities.
Eagle ray | Majestic ray with dramatic wing-like fins and long tail; popular in tropical regions for its leaps.
Earthworm eel | Slender, burrowing fish reminiscent of earthworms, adept at navigating sediments.
Eel | Widely distributed elongated fish, some migrate thousands of kilometers to spawn; mysterious life cycles.
Eel cod | Cod-like fish with an eel’s body, found in southern hemisphere deep-sea habitats.
Eel-goby | Goby species with a serpentine body profile, found in marine mudflats and brackish waters.
Eelpout | Bottom-dwelling eel-shaped fish inhabiting cold seas, known for vibrant snout colors.
Eeltail catfish | Catfish sporting an eel-like extended tail; common in tropical waters.
Elasmobranch | Class including sharks, rays, and skates; cartilaginous skeleton and rich evolutionary history.
Electric catfish | African catfish capable of delivering strong electric shocks for hunting and deterrence.
Electric eel | Powerful South American freshwater fish capable of generating substantial electric current.
Electric knifefish | South American fish with weak electric fields for navigation and communication.
Electric ray | Flat marine predator delivering impressive electric shocks to stun prey or ward off threats.
Elephant fish | Fish marked by a trunk-like snout; several species display unusual elongated noses.
Elephantnose fish | African river fish famous for sensitive probing trunk and sophisticated electric sense.
Elver | Juvenile stage of the eel; migrates from ocean back to freshwater where it matures.
Ember parrotfish | Dazzling, flame-red reef parrotfish, engaging in sand-manufacturing on reefs.
Emerald catfish | Green-tinged, peaceful aquarium catfish, lively and easy to care for.
Emperor | Name for several impressive reef fish with regal size and coloration.
Emperor angelfish | Large, vividly striped reef angelfish; a showpiece of tropical marine tanks.
Emperor bream | Bream species with stately size from Indo-Pacific coral habitats.
Escolar | Deep-sea fish with oily flesh, sometimes toxic if overeaten; marketed as 'white tuna'.
Eucla cod | Australian deep-sea cod species found on continental slopes; rarely captured.
Eulachon | Small, oily Pacific Northwest fish, once used for food, oil extraction, and ceremonial events.
European chub | Widely distributed freshwater fish in Europe, hardy and popular among anglers.
European eel | Mysterious migratory fish, traveling thousands of miles to its birthplace in the Sargasso Sea.
European flounder | Flattened, bottom-dwelling fish from European coasts, blending well with sandy beds.
European minnow | Small, lively cyprinid found in rivers and lakes throughout Europe.
European perch | Defining freshwater fish with bold stripes, prized for sport and culinary qualities.
False brotula | Deep-sea species closely resembling brotula, inhabiting oceanic trenches.
False cat shark | Deceptively similar to true catsharks; rare deep-sea shark found off southern continents.
False moray | Eel-like fish with similar appearance to morays, but with distinct anatomical differences.
False trevally | Indo-Pacific coastal fish, often confused with true trevallies for body shape and coloration.
Fangtooth | Deep-sea predator boasting proportionally giant teeth; adapted to dark, pressurized depths.
Fathead sculpin | Odd, large-headed deep-sea sculpin with unique adaptations for abyssal life.
Featherback | Fish with a flowing, feather-like dorsal fin; includes popular aquarium species in Asia.
Fierasfer | Pearlfish notorious for living inside sea cucumbers or shellfish, often surfacing at night.
Filefish | Flat-bodied, rough-skinned reef fish that rely on camouflage and tough hides for defense.
Finback cat shark | Distinctive cat shark with pronounced dorsal fin, native to deep Asian seas.
Fingerfish | Small, finger-shaped fish found in both fresh and brackish habitats; playful and social.
Fire bar danio | Dazzling, brightly striped danio, highly sought after for lively aquarium displays.
Fire goby | Brilliantly colored reef fish with an energetic darting swimming style.
Firefish | Small, radiant reef fish, prized for fiery red or orange highlights.
Flabby whale fish | Deep-sea fish with a loose, flabby body; rarely seen by humans.
Flagblenny | Playful blenny species marked by bold, flag-like dorsal fin.
Flagfin | Group of fish featuring distinctive flag-shaped fins.
Flagfish | Petite aquarium fish sporting flag-like patterns on the tail.
Flagtail | Fish with eye-catching, flag-like tail markings, found in fresh and brackish waters.
Flashlight fish | Deep-sea species with bioluminescent organs beneath the eyes, glowing in dark waters.
Flatfish | Group of flattened, often bottom-dwelling fish, including flounder, sole, and turbot.
Flathead | Adaptable bottom-dwelling predator with a broad, flat head; popular in Australian fishing.
Flathead catfish | Large, predatory North American freshwater catfish, noted for the flat skull.
Flier | Small sunfish species with rounded fins; found in rivers and ponds in the southeastern US.
Flounder | Bottom-dwelling, flattened fish camouflaged against sandy sea floors; several popular edible species.
Flying fish | Fascinating fish capable of long glides above the ocean surface using wing-like pectoral fins.
Flying gurnard | Decoratively winged fish capable of short glides and startling displays.
Footballfish | Deep-sea anglerfish with a football-shaped body and a luminous lure; rarely seen alive.
Forehead brooder | Small fish that uniquely carries eggs bonded to its forehead until hatching.
Four-eyed fish | Unique species with divided eyes, allowing simultaneous vision above and below water.
French angelfish | Large, vibrantly colored reef angelfish, beloved by divers and aquarists.
Freshwater eel | Elongated, serpentine fish found in lakes and rivers, some capable of epic migrations.
Freshwater hatchetfish | Hatted-shaped, silvery aquarium favorite, known for occasional aerial leaps.
Freshwater shark | General name for various freshwater fish with shark-like dorsal fins; not true sharks.
Frigate mackerel | Slim, swift oceanic mackerel; important forage for larger predators.
Frilled shark | Primitive, deep-sea shark with frilly gill structures and a prehistoric lineage.
Frogfish | Masterful ambush predator, covered in camo; uses a “lure” on its head to attract prey.
Frogmouth catfish | Catfish with an impressively wide mouth, suited for gulping up prey from the bottom.
Fusilier fish | Rapid, silver-blue schooling reef fish; integral to Indo-Pacific food webs.
Galjoen fish | South African coastal favorite, highly esteemed in local sport and cuisine.
Ganges shark | Critically endangered, rare freshwater shark from India’s sacred rivers.
Gar | Ancient, elongated freshwater fish with needle-like jaws and armored scales.
Garden eel | Slender eel that buries most of its body vertically in the sand, waving gently to feed.
Garibaldi | Iconic, vibrant orange fish from California reefs; the state’s official marine fish.
Garpike | Alternative name for gars; predatory, ancient fishes of North American rivers and lakes.
Ghostfish | Deep-sea fish with pale, ghostly appearance; rarely encountered at human-accessible depths.
Ghost flathead | Eerie, pale flathead species adapted for life in deep ocean environments.
Ghost knifefish | South American aquarium favorite capable of generating mild electric fields.
Ghost pipefish | Pipe-shaped reef fish boasting remarkable camouflage and secretive habits.
Ghost shark | Deep-sea cartilaginous fish, close relatives of sharks and rays; metallic shine.
Ghoul | Gruesome-looking deep-sea fish with grotesque adaptations to abyssal life.
Giant danio | Large, swift danio species; lively schoolers ideal for spacious aquariums.
Giant gourami | Substantial, peaceful aquarium fish loved for their size and gentleness.
Giant sea bass | Massive, endangered Pacific coast fish, now subject to strict conservation efforts.
Gibberfish | Deep-sea fish with conspicuously large mouth and small eyes.
Gila trout | Rare, threatened trout found only in Southwestern US creeks; centerpiece for native fish conservation.
Gizzard shad | Common North American fish with an enlarged “gizzard” stomach for processing plant material.
Glass catfish | Delicate, transparent aquarium catfish that exhibit shimmering schooling behavior.
Glass knifefish | Translucent knifefish from South America; notable for weak electrical signaling.
Glassfish | Group of transparent aquarium fish; interesting to watch because of their visible organs.
Glowlight danio | Small, glowing-striped freshwater aquarium fish with lively schooling drive.
Goatfish | Bright, active reef fish using whisker-like barbels to detect food in sand.
Goblin shark | Deep-sea “living fossil” with bizarre, extendable jaw and translucent pink skin.
Goby | Highly diverse, small bottom-dwelling fish, essential to reef and river communities.
Golden dojo | Gold-colored variant of the dojo loach; lively, burrowing aquarium fish.
Golden loach | Brilliantly colored freshwater loach favored in aquaria for its beauty.
Golden shiner | Radiant, golden bait fish, vital to North American pond and lake ecosystems.
Golden trout | Celebrated, vivid California trout species famed for their colors and rarity.
Goldeye | North American freshwater fish with bright gold eyes and silvery body.
Goldfish | Among the world’s most popular ornamental fish; hundreds of breeds, colors, and fin shapes.
Gombessa | Remarkable coelacanth “living fossil”; prized among scientists and divers.
Goosefish | Deep-sea anglerfish with grotesque, expandable jaw and bioluminescent lure.
Gopher rockfish | Striking rockfish native to Pacific coastal waters; beloved in sport fishing.
Gourami | Diverse group of labyrinth-breathing aquarium fish, famed for variety and striking looks.
Grass carp | Large, herbivorous freshwater fish used worldwide to manage aquatic vegetation.
Graveldiver | Small fish adapted to burrowing or hiding among gravel and sediments.
Gray mullet | Common coastal fish identified by its gray coloration and forked tail.
Gray reef shark | Energetic, social reef shark frequently seen in tropical coral ecosystems.
Grayling | Salmonid with ornate, sail-like dorsal fin; sought after for its beauty and spirited fights.
Great white shark | Apex ocean predator, renowned globally for power, intelligence, and sheer size.
Dichotomyctere nigroviridis|Green spotted puffer | Brackish aquarium pufferfish with vivid green spots; may inflate itself for defense.
Green swordtail | Versatile, brightly colored aquarium livebearer; features a dramatic sword-shaped tail.
Greeneye | Deep-sea oddity with glowing green eyes; helps with vision in the deep darkness.
Greenling | North Pacific coastal fish popular in sport and commercial fishing.
Grenadiers | Deep-sea group noted for long tapering tails and large eyes; also called rattails.
Ground shark | Major family including everyday shark species, such as requiem and houndsharks.
Grouper | Stout, brawny reef predator; several species grow to massive sizes and are prized for food.
Grunion | Small, silvery fish famous for spawning runs on sandy beaches at night.
Grunt | Reef fish famed for grunting sounds produced with their swim bladders.
Grunt sculpin | Odd, spiny Pacific fish, lively and well camouflaged among rocky reefs.
Grunter | Freshwater species able to emit grunting noises; important in Asian aquaculture.
Gudgeon | Diminutive, bottom-dwelling freshwater fish with subtle colors and active behavior.
Guitarfish | Flattened ray with guitar-shaped body; found in shallow sandy habitats.
Gulf menhaden | Critical forage fish in Gulf of Mexico; source of fish oil and omega-3 supplements.
Gulper | Deep-sea fish with an extraordinary extendable mouth, able to consume prey larger than its body.
Saccopharynx|Gulper eel | Deep-sea eel sporting massive “gaping” mouth; capable of swallowing sizable prey.
Gunnel | Elongated, eel-like fish found in marine rocky habitats; recognized for rapid darting movements.
Guppy | Endlessly varied, colorful aquarium favorite; well known for ease of breeding and adaptability.
Gurnard | Bottom-dwelling fish with wing-like pectoral fins; uses “legs” to walk along the sea floor.
Haddock | North Atlantic commercial fish highly esteemed for its lean, white flesh and subtle flavor.
Hagfish | Primitive, jawless slime-producing fish; key for deep-sea nutrient cycling and scientific research.
Hairtail | Long, ribbon-shaped predator with shimmering silver coloration; found in tropical and subtropical seas.
Hake | Family of commercial white-fleshed fish from both Atlantic and Pacific oceans.
Halfbeak | Slender fish with extended lower jaw; found in tropical and subtropical marine environments.
Halfmoon | Small, moon-shaped reef species often seen darting around kelp forests.
Halibut | Massive, flat-bodied food fish central to northern commercial fisheries; mild, firm flesh.
Halosaur | Deep-sea fish with prolonged tail fin; uncommon and adapted for life in abyssal depths.
Hamlet | Small, colorful reef fish known for fascinating simultaneous hermaphroditic reproduction.
Hammerhead shark | Instantly recognizable by flattened “hammer” head; uses specialized sensors for hunting.
Hammerjaw | Deep-sea fish with powerful jaws and fearsome teeth; seldom encountered.
Handfish | Rare Australian fish that “walks” along the seabed using broad, pectoral fins.
Hardhead catfish | Catfish with rigid, bony skull; frequent in southern North American coastal waters.
Harelip sucker | Rare, specialized freshwater sucker fish endemic to North America.
Hatchetfish | Deep-sea or freshwater fish with distinct, hatchet-shaped body; known for crunching flight.
Hawkfish | Small reef dwellers adept at perching and sudden ambushes; active and colorful.
Herring | Worldwide schooling fish, fundamental to food webs and commercial fishing.
Herring smelt | Small, silvery fish resembling herring; vital in northern ecosystems.
Hickory Shad | Migratory shad species from eastern USA rivers and bays; valued by recreational anglers.
Hillstream loach | Loach adapted for life in fast-flowing streams and waterfalls; clings tightly to rocks.
Hog sucker | Bottom-feeding freshwater fish with unique snout for rooting in substrates.
Hoki | Commercially important fish from New Zealand; fillets used in fast food and white fish markets.
Horn shark | Small, slow-moving shark with prominent horn-like dorsal fin; found off California and Australia.
Horsefish | Name for seahorses and related species; prized for their bizarre upright posture and parental behavior.
Houndshark | Group of small, slender sharks with swift movements and social behaviors.
Huchen | Large, endangered European salmonid; highly prized sportfish with a long lifespan.
Humuhumunukunukuapua'a | Colorful, iconic Hawaiian triggerfish; state fish and essential to coral reefs.
Hussar | Small, schooling Pacific reef fish with flashy coloring and rapid movement.
Channichthyidae|Icefish | Antarctic fish family with transparent blood and unique adaptations to freezing waters.
Ide | European freshwater fish noted for its shiny scales and occasional orange fins.
Ilish|Ilish/Hilsha | Revered South Asian food fish, central to Bengali cuisine and traditions.
Inanga | Silvery, agile freshwater fish in New Zealand; key part of whitebait fishery.
Stenodus nelma|Inconnu | Large, migratory Arctic salmonid; subject of commercial and sport fishing.
Jack | Catch-all for several swift, predatory fish species, including jacks and trevallies.
Jack Dempsey | Stunning, aggressive aquarium cichlid with neon blues and bold personality.
Japanese eel | Migratory eel species central to Japanese cuisine; notable for epic spawning journey.
Javelin | Deep-sea fish with pointed, spear-like body; expert at quick vertical migration.
Jawfish | Fascinating burrowers that brood eggs in their large, expandable mouths.
Jellynose fish | Deep-sea fish with jelly-like, elongated snout and soft tissues.
Jewel tetra | Sparkling, vividly colored aquarium tetra; easy to care for and bred widely.
Jewelfish | Eye-catching cichlid from Africa, featuring metallic spots and intense territoriality.
Jewfish | Historical name for Goliath grouper; largest groupers found in warm coastal waters.
John Dory | Deep-bodied, predatory fish with a signature dark spot; celebrated in European cuisines.
Kafue pike | Pike species native to Zambia’s Kafue river system.
Kahawai | Agile, strong New Zealand coastal fish; favorite among local anglers and communities.
Kaluga | Gigantic Russian sturgeon famed for its caviar; critically endangered.
Kanyu | Small, ornamental Asian freshwater species, known for their gentle behavior.
Kelp perch | Resident perch of temperate kelp forests; slender and well camouflaged.
Kelpfish | Elusive, slender fish vanishing among kelp fronds in rocky Pacific shallows.
Killifish | Small, usually brightly colored freshwater fish with incredible survival adaptations.
King of the herrings | Oarfish, legendary for its length and mysterious deep-sea life.
King-of-the-salmon | Rare Pacific deep-sea fish with regal, elongated body.
Kingfish | Umbrella term for various swift marine predators, highly sought by anglers.
Kissing gourami | Lively gourami known for their unique “kissing” social gestures.
Knifefish | Elongated, weakly electric freshwater fish found in South American rivers.
Knifejaw | Saltwater fish with toothy, knife-like jaws; powerful grazers of rocky reefs.
Koi | Ornamental carp celebrated for spectacular colors and patterns, iconic in garden ponds.
Kokanee | Landlocked version of sockeye salmon, found in cold North American lakes.
Kokopu | New Zealand freshwater fish, part of the country’s prized whitebait.
Kuhli loach | Small, eel-resembling Asian loach; popular and peaceful in aquariums.
Labyrinth fish | Air-breathing species blessed with intricate labyrinth organs; includes gouramis and bettas.
Ladyfish | Slender, silvery coastal fish known for acrobatic leaps and rapid schooling.
Lake chub | Hardy freshwater fish from North American lakes and ponds; important in food chains.
Lake trout | Large, cold-water predator; favorite in North American deep lakes.
Lake whitefish | North American commercial fish, mild-flavored and highly sustainable.
Lampfish | Deep-sea lanternfish with glowing organs and vertical migration behavior.
Lamprey | Jawless, parasitic fish whose larvae play essential roles in aquatic ecosystems.
Lancetfish | Razor-slender deep-sea fish equipped for rapid chases at depth.
Lanternfish | Vital deep-sea group featuring bioluminescent “lanterns”; forms basis of many food webs.
Largemouth bass | Iconic, aggressive North American game fish with cavernous mouth.
Leaf Fish | Masterful ambush predator; resembles decaying leaves to trick prey in tropical streams.
Leatherjacket | Durable-skinned fish sporting tough, leathery scales; includes various triggerfish and relatives.
Lefteye flounder | Flatfish with both eyes on the left side; effective benthic camouflage artist.
Lemon shark | Sturdy, yellow-tinged shark, widely studied for social and migratory tendencies.
Lemon sole | Appetizing European flatfish with a unique pale yellow sheen and sweet flavor.
Lemon tetra | Petite, yellow-hued aquarium tetra full of energy and charm.
Lenok | Asian salmonid fish found in cold rivers, sporting unique coloration and valued by anglers.
Leopard danio | Spotted, lively aquarium danio; active, peaceful and easy to breed.
Lightfish | Deep-sea dwellers equipped with photophores for light emission and communication.
Limia | Peaceful, small aquarium livebearer; active and easy to care for.
Lined sole | Flatfish with distinct, beautiful linear patterns along the body.
Ling | Large, Atlantic cod-like fish found deep in cold waters; prized for firm fillets.
Ling cod | Aggressive, heavy Pacific fish known for its imposing mouth and blue-green flesh.
Lionfish | Magnificent, striped reef predator equipped with venomous spines; invasive in many regions.
Livebearer | Fish species that give birth to live young, including guppies, mollies, and swordtails.
Lizardfish | Swift, lizard-like fish with pointed snout; efficient ambush predator.
Loach | Large family of small, bottom-dwelling freshwater fish; active, peaceful, and diverse.
Loach catfish | Catfish representing loach-like qualities; found in African and Asian rivers.
Loach goby | Goby species mimicking the elongated shape of loaches; playful aquarium resident.
Loach minnow | Small, endangered freshwater fish native to the southwestern USA.
Longfin | Refers generally to fish species sporting elegantly long fins.
Longfin dragonfish | Deep-sea dragonfish with extravagantly long fins extending from the body.
Longfin escolar | Deep-sea fish with flowing fins and iridescent scalation.
Longfin smelt | Slender, silvery fish with pronounced fin length; vital in cold North American rivers.
Long-finned char | Salmonid marked by especially elongated fins.
Long-finned pike | Pike species exhibiting strikingly long fins; rare but impressive predator.
Long-finned sand diver | Sand-dwelling fish with elongated fins for maneuvering through substrate.
Longjaw mudsucker | Mud-dwelling fish with extended, flexible jaw for reaching prey.
Longneck eel | Eel with unusual neck length suited for navigating narrow crevices.
Longnose chimaera | Deep-sea cartilaginous fish with elongated snout; closely related to ghost sharks.
Longnose dace | Small, swift freshwater minnow with an elongated snout.
Longnose lancetfish | Deep-sea predator with spear-like, elongated snout, adept at rapid movement.
Longnose sucker | Robust freshwater fish with pronounced, tubular snout for extracting food from sediment.
Longnose whiptail catfish | Catfish with extremely long tail, used for defense and sensing.
Long-whiskered catfish | Catfish sporting exaggerated barbels for exploration and foraging.
Loosejaw | Deep-sea predator featuring a disconnected, highly extendable jaw.
Lost River sucker | Critically endangered Oregon freshwater fish, focus of local conservation efforts.
Louvar | Rare, deep-bodied migratory ocean fish, notable for its size and striking profile.
Loweye catfish | Catfish marked by low-set eyes for intricating bottom foraging.
Luderick | Australian coastal fish recognized by bold stripes and herbivorous habits.
Luminous hake | Deep-sea hake species furnished with glowing light organs.
Lumpsucker | Odd, round suction-cup fish adept at clinging to rocks; some have spectacular colors.
Lungfish | Primitive air-breathing fish with remarkable resilience and evolutionary significance.
Mackerel | Torpedo-shaped, fast schooling fish, crucial for fisheries and valued for flavor and oils.
Mackerel shark | Broad group including famous great white, mako, and other swift predators.
Madtom | Tiny North American catfish species, some equipped with mild venomous spines.
Mahi-mahi | Vivid, iridescent sport fish renowned for acrobatics and rapid growth in tropical oceans.
Mahseer | Majestic, large Asian river fish celebrated by anglers and central to local watersheds.
Mail-cheeked fish | General group characterized by pronounced bony plates shielding the cheeks.
Mako shark | Pinnacle of ocean speed and predation, this shark is famed for leaps and formidable teeth.
Mandarinfish | Tiny reef jewel with electrifying blue and orange patterns; highly sought in home aquaria.
Manefish | Elegant deep-sea fish exhibiting mane-like fin rays for display and defense.
Man-of-war fish | Specialist fish living among Portuguese man-of-war tentacles, immune to their stings.
Manta ray | Giant, graceful plankton-feeder, famed for enormous wingspan and gentle nature.
Marblefish | Fish renowned for mottled, marbled coloration; excellent at blending into rocky habitats.
Marine hatchetfish | Deep-sea version of the hatchetfish, equipped with intense photophores for night feeding.
Marlin | Highly migratory billfish, legendary in sport fishing for size, speed, and endurance.
Masu salmon | Salmon species intrinsic to East Asian rivers, featuring vivid spawning colors.
Medaka | Hardy, tiny Japanese fish often used in genetics research and home aquariums.
Medusafish | Deep-sea fish with jelly-like body and mysterious, drifting habits.
Megamouth shark | Massive, rare filter-feeder; recently discovered, deep ocean marvel.
Menhaden | Crucial Atlantic forage fish, harvested for oil and animal feed.
Merluccid hake | Hake species vital to Atlantic fisheries, mild flavor and white flakes.
Mexican golden trout | Strikingly colored native Mexican trout, central to local conservation.
Midshipman fish | Nocturnal, noise-making fish with light-producing “buttons” on the body.
Milkfish | Asian aquaculture staple, beloved for soft flesh and rapid growth.
Minnow | Tiny, versatile freshwater cyprinids populating streams, ponds, and aquariums globally.
Minnow of the deep | Deep-sea cousin of minnows; mysterious adaptations for abyssal life.
Modoc sucker | Rare, endangered freshwater fish found only in California and Oregon.
Mojarra | Small, silver coastal fish widespread in tropical waters; popular in Latin American cuisine.
Mola mola | Enormous, sunbathing ocean sunfish; world’s heaviest bony fish.
Monkeyface prickleback | Eel-shaped Pacific fish with grumpy “monkey-like” features; hides among rocks.
Monkfish | Deep-sea anglerfish, celebrated for rich flavor and firm white texture in gourmet cooking.
Mooneye | Silvery North American fish, known for large, reflective eyes and flash schooling.
Moonfish | Deep-bodied, round ocean fish; distinctive for their flattened, silver forms.
Moorish idol | Exotic black-white-yellow reef fish; difficult to keep but adored worldwide.
Mora | Rare, deep-sea cod-like fish with subtle patterns and elusive lifestyles.
Moray eel | Elongated, nocturnal reef predator; feared for powerful bite and snake-like movements.
Morid cod | Deep-sea cod relatives with distinctive features; important in deep-water fisheries.
Morwong | Australian coastal fish marked by bold vertical stripes and thick lips.
Moses sole | Camouflaged flatfish from the Red Sea and Indian Ocean reefs.
Mosquitofish | Prolific, livebearing fish used worldwide to control mosquito populations.
Mouthbrooder | Fish species whose adults protect and incubate eggs (or young) in their mouths.
Mozambique tilapia | Hardy, adaptable African cichlid exported globally for aquaculture.
Mrigal | Robust Indian carp species popular in regional farming and cuisine.
Mud catfish | Bottom-dwelling catfish found in muddy rivers and ponds; tough, adaptable, and important in fisheries.
Mud minnow | Small, mud-dwelling fish with high tolerance for low oxygen.
Mudfish | Catch-all for multiple fish species specialized for muddy, low-oxygen zones.
Mudskipper | Amphibious fish able to walk on land and climb mangroves with strong pectoral fins.
Mudsucker | Fish adapted for burrowing and living within mud, notable for low oxygen tolerance.
Mullet | Fork-tailed, gray coastal fish fundamental to cuisine and coastal ecology worldwide.
Mummichog | Tiny, hardy coastal fish able to survive wide salinity and temperature fluctuations.
Murray cod | Australia’s largest freshwater predator, central to river ecosystems and folklore.
Muskellunge | Elusive, powerful North American freshwater fish; top prize for many anglers.
Mustache triggerfish | Reef triggerfish adorned with mustache-like facial markings and defensive behaviors.
Mustard eel | Eel species marked by yellowish hues; found in tropical rivers.
Naked-back knifefish | Unique knifefish with exposed back, native to Amazon river basins.
Nase | European river fish with prominent snout; active feeder in flowing waters.
Needlefish | Sleek, needle-like fish inhabiting surface waters; swift, predatory habits.
Neon tetra | Small, glowing blue and red aquarium staple; peaceful and easy to breed.
New World rivuline | Livebearing fish group from the Americas, adapted for life in changing waters.
New Zealand sand diver | Agile, elongated sand dweller from New Zealand coasts.
New Zealand smelt | Small, silvery fish endemic to rivers and lakes in New Zealand.
Nibble fish | Fish used in spa therapy to nibble away dead skin; found in warm Asian streams.
Noodlefish | Tiny, thread-like fish living in oceanic or freshwater zones; little is known about their ecology.
North American darter | Diminutive, brilliantly colored stream fish; important for biodiversity.
North American freshwater catfish | Diverse assemblage of catfish found across rivers, ponds, and lakes.
North Pacific daggertooth | Deep-sea predator marked by dagger-shaped teeth and swift attacks.
Northern anchovy | Abundant schooling fish in Pacific nutrient cycles and seafood products.
Northern clingfish | Clingfish found in northern coastal waters, renowned for super-strong suction discs.
Northern lampfish | Luminous deep-sea lanternfish found throughout northern oceanic regions.
Northern pike | Iconic, torpedo-shaped freshwater predator armed with sharp teeth and lightning speed.
Northern sea robin | Bottom-dweller with wing-like fins, often found in shallow northern waters.
Northern squawfish | Large native North American fish; important in river food webs.
Northern stargazer | Bizarre bottom fish with eyes peering up from sandy substrate; packs an electric shock.
Nototheniidae|Notothen | Antarctic fish family with antifreeze proteins and robust tolerance of subzero temperatures.
Nurse shark | Slow-moving, carpet-like shark with small , blunt teeth; peacefully inhabits reefs and lagoons.
Nurseryfish | Unusual fish that secures eggs externally on male’s forehead until hatching.
Oarfish | Mystical deep-sea fish; record-holder for longest bony fish, infrequently observed.
Ocean perch | Deep-sea, bright red fish; essential in North Pacific commercial harvesting.
Ocean sunfish | Giant, circular open-ocean fish found worldwide; famous for sun basking.
Oceanic whitetip shark | Indomitable oceanic shark with telltale white-tipped fins; travels immense distances.
Oilfish | Deep-sea fish with oily flesh and peculiarities; excessive consumption may cause digestive issues.
Old World knifefish | Elongated knifefish found in African and Asian rivers.
Oldwife | Australian fish with distinctive shape and mesmerizing bands; often found in coastal reefs.
Olive flounder | Flatfish with olive-green tones; prominent in Asian culinary uses.
Opah | Colorful, round ocean fish, notable as the only known fully warm-blooded fish.
Opaleye | Coastal fish with shimmering opal-like eyes and strong herbivorous diet.
Orange roughy | Deep-sea, slow-growing fish; highly prized, but overfished due to longevity and taste.
Orangespine unicorn fish | Striking reef fish featuring orange spines and a unicorn-like protrusion.
Orangestriped triggerfish | Reef triggerfish displaying vivid orange stripes; energetic and territorial.
Orbicular batfish | Circular, disc-shaped reef fish popular in marine aquariums.
Orbicular velvetfish | Small, velvet-skinned fish blending seamlessly into reef crevices.
Oregon chub | Endangered Oregon river fish; significant effort underway to restore its populations.
Orfe | European freshwater fish, metallic silver-gold coloration; lively and suited to garden ponds.
Oriental loach | Loach species found across Asia, noted for adaptable and peaceful traits.
Oscar | Aggressive, intelligent cichlid native to South America; interactive pet in large aquariums.
Owens pupfish | Critically endangered Californian pupfish; signature species for fish conservation.
Pacific albacore | Key Pacific tuna species, celebrated for excellence in canning and grilling.
Pacific cod | Foundation of North Pacific commercial fisheries; mild, flaky flesh.
Pacific hake | North Pacific whitefish widely used in global food markets.
Pacific herring | Abundant schooling fish, backbone of North Pacific fisheries.
Pacific lamprey | Migratory lamprey with historic importance for indigenous peoples in Pacific Northwest.
Pacific rudderfish | Deep-water Pacific species occasionally netted in commercial harvest.
Pacific salmon | Includes all Pacific salmon species; essential for ecology, industry, and cuisine.
Pacific saury | Slender ocean fish beloved in East Asian cuisine for smoky, oily flavor.
Pacific trout | Group of trout species hailing from Pacific regions, including rainbow and cutthroat.
Pacific viperfish | Deep-sea predator with glowing lure and formidable, fang-like teeth.
Paddlefish | Primitive North American freshwater filter-feeder, featuring a unique paddle-shaped snout.
Pancake batfish | Ridiculously flat deep-ocean anglerfish with an unusual gait and odd feeding style.
Iridescent shark|Panga | Highly farmed Southeast Asian catfish; fast growth and mild flavor.
Paradise fish | Hardy, flamboyant aquarium fish with beautiful, trailing fins and vivid coloring.
Parasitic catfish | Amazon species notorious for parasitizing gills and body cavities of larger fish.
Girella tricuspidata|Parore | Southern Pacific coastal fish, common in rocky reefs and estuaries.
Parrotfish | Reef icon famous for parrot-like beak and sand-manufacturing from algae-covered coral.
Peacock flounder | Flatfish with elaborate “peacock eyespots”; extraordinary camouflage artist.
Peamouth | Small, silvery North American fish thriving in cool, clear streams.
Pearl danio | Small, shimmering aquarium favorite, lively and tolerant of varied water conditions.
Pearl perch | Brightly shining coastal fish, esteemed for edible texture and taste.
Pearleye | Seldom-seen deep-ocean fish with luminous pearl-like eye adaptations.
Pearlfish | Unique fish that resides within sea cucumbers, emerging to feed at night.
Pelagic cod | Cod species inhabiting open waters; rarely fished but key to deep-water webs.
Pelican eel | Deep-sea fish equipped with enormous expandable mouth; can swallow very large prey.
Pelican gulper | Deep-sea predator related to the gulper eel, packs an epic, expandable jaw.
Pencil catfish | Petite, slender South American catfish, popular in small planted aquariums.
Pencilfish | Small, pencil-shaped schooling aquarium fish bursting with color and vitality.
Pencilsmelt | Thin, elongated smelt species agrressive in shoals and important forage for larger fish.
Peppered corydoras | Spotted, hardy aquarium catfish, renowned for peaceful nature and ease of community.
Perch | Fundamental game fish in Europe and North America; recognized by vertical stripes and sharp spines.
Peters' elephantnose fish | African electric fish noted for trunk-like snout and advanced sensory systems.
Pickerel | Small predatory freshwater fish related to pike; swift and aggressive.
Pigfish | Grunt species with a distinctive snout and pig-like vocalizations; popular in southern coastal fishing.
Pike | Large, voracious freshwater predator, attacking with lightning speed and long, pointed body.
Pike conger | Powerful, eel-like predator found in Japanese and Asian waters.
Pike eel | Elongated eel with a pike-style snout and formidable bite.
Pikeblenny | Slender blenny species with elongated body, often seen in rocky coastal zones.
Pikeperch | Effective freshwater predator combining qualities of pike and perch; prized by European anglers.
Pilchard | Small, abundant schooling fish; forms a staple for canned food and Mediterranean cuisine.
Pilot fish | Iconic, striped ocean fish traveling alongside sharks and rays; mutualistic symbiosis.
Pineapplefish | Night-active reef fish with scale armor resembling pineapples and glow-producing organs.
Pineconefish | Small armored fish covered with pinecone-like scales; bioluminescent for nighttime vision.
Pink salmon | Smallest Pacific salmon, renowned for immense spawning runs and pale pink flesh.
Píntano | Term for various South American freshwater fish species from slow rivers.
Pipefish | Slender, pipe-shaped relative of seahorses; camouflaged in seagrass and tidal pools.
Piranha | Infamous, razor-toothed carnivore of South American rivers; misrepresented in folklore.
Pirarucu | Giant, air-breathing Amazonian fish, fundamental in indigenous culture and cuisine.
Pirate perch | Eccentric US native freshwater fish with unusual forward-situated anus.
Plaice | Popular European flatfish, delicious with mild flavor and tender texture.
Platy | Lively, easy-breeding aquarium fish with endless color varieties.
Platyfish | Small, ornamental aquarium livebearer with playful swimming and colorful patterns.
Pleco | Boris armored catfish, famous for extending sucker mouth to clinging on glass and devouring algae.
Plownose chimaera | Deep-sea chimaera with unconventional plow-shaped snout; rarely seen by scientists.
Poacher | Armored bottom-dweller, often with odd body shapes; thrives in cold marine environments.
Pollock | Backbone of commercial whitefish industry; used in fish sticks and surimi.
Pollyfish | Petite, peaceful freshwater fish from Eurasia.
Pomfret | Deep-bodied, shiny oceanic fish; esteemed in Asian kitchens for flavor and texture.
Pompano | Silvery, fast coastal fish highly esteemed as sport and fine food.
Pompano dolphinfish | Dolphinfish species with signature streamlined, silvery body.
Ponyfish | Peculiar, small silvery fish notable for a jaw that can be protruded dramatically.
Popeye catalufa | Reef fish bearing conspicuously large, bulging eyes.
Porbeagle shark | Cold-water shark with muscular body, closely related to makos and great whites.
Porcupinefish | Inflates and deploys sharp spines when threatened; some species highly toxic.
Porgy | General name for several chunky coastal fish; beloved as seafood in Mediterranean and Caribbean.
Port Jackson shark | Small Australian shark with unique harness-like markings.
Powen | European whitefish, member of the salmon family; subtle flavors in classic fish dishes.
Prickleback | Slender, spiny fish common among rocks and kelp; flexible and camouflaged.
Pricklefish | Deep-sea species bristling with sharp prickles; adapted for abyssal defense.
Prickly shark | Rare, deep-sea shark distinguished by thick skin covered with visible prickles.
Prowfish | Deep-sea fish marked by upward-sloping head and unusual shape.
Pufferfish | Inflatable, round-bodied fish; many species highly dangerous due to tetrodotoxin poison.
Pumpkinseed | Colorful North American sunfish, easy to catch and popular for children.
Pupfish | Small, resilient fish surviving in harsh conditions; emblematic of freshwater biodiversity.
Pygmy sunfish | Tiny sunfish native to America's southern swamps and streams.
Queen danio | Small, sparkling aquarium danio species; active and peaceful.
Queen parrotfish | Large, flamboyant Caribbean reef parrotfish; forms sand from coral chewing.
Queen triggerfish | Vividly colored reef triggerfish recognized by elongated tail fin and striking profile.
Quillback | Robust North American freshwater fish with a distinctive quill-shaped dorsal fin.
Quillfish | Slim, quill-shaped deep-sea fish, well suited for burrowing and hiding.
Rabbitfish | Herbivorous reef fish equipped with venomous spines for defense; supports coral health.
Raccoon butterfly fish | Reef fish sporting raccoon-like facial mask; social and strikingly colored.
Ragfish | Soggy, soft-bodied deep-sea fish with jelly-like texture, peculiar among deep-water fauna.
Rainbow trout | World renowned cold-water sport fish; iconic rainbow flank stripe.
Rainbowfish | Rainbow-hued small freshwater fish from Australasia; lively and cheerful in aquariums.
Rasbora | Tiny, schooling Asian freshwater fish; notable for color, speed, and social ease.
Ratfish | Deep-sea chimaera species with rat-like tail and fascinating evolutionary traits.
Rattail | Deep-sea group with elongated, whip-like tails; scavengers of the ocean floor.
Batoidea|Ray | Broad group including rays and skates; characterized by flat bodies and wing-like pectoral fins.
Razorback sucker | North American endangered sucker fish; central to river restoration efforts.
Razorfish | Slender, razor-angled reef fish, gliding vertically among seagrasses.
Red grouper | Popular Southeastern US game and food fish; rich flavor and strong fighting ability.
Red salmon | Sockeye salmon known for bright red coloration and exceptional culinary reputation.
Red Snapper | Coveted red-hued sport and food fish throughout the world’s warm coastal waters.
"

set greeting_art "\
                               X         
 XXXXXX XX XXXXXX XX  XX      XX         
 XX     XX XX     XX  XX    XXXXXX       
 XXXXX  XX XXXXXX XXXXXX  XXXXXXXXXXX  X 
 XX     XX     XX XX  XX XX  XXXXXXXXXX  
 XX     XX XXXXXX XX  XX  XXXXXXXXXXX  X 
                               X         
"

function greet_echo
    set -l pos $argv[1]
    set -l fg '▓'
    # set -l bg '░'
    set -l bg '~'

    set width (tput cols)
    if test $width -lt 40
        return
    end
    set art_width 41
    set padding (math floor (math "($width - $art_width) / 2"))
    for i in (seq $padding)
        echo -n $bg
    end

    echo -n $greeting_art | string split \n | sed -n $pos | sed -e "s/X/$fg/g" -e "s/ /$bg/g" | tr \n x | sed -e s/x//g

    for i in (seq $padding)
        echo -n $bg
    end
    # If padding * 2 + art_width < width, add one more space
    if test (math "$padding * 2 + $art_width") != $width
        echo -n $bg
    end
    echo
end

function greet
    # Colored ASCII greeting
    set_color red
    greet_echo 1p
    set_color yellow
    greet_echo 2p
    set_color green
    greet_echo 3p
    set_color magenta
    greet_echo 4p
    set_color blue
    greet_echo 5p
    greet_echo 6p
    greet_echo 7p
end

function get_fish
    echo -n $fish_list | sed -n "$argv[1]{p}" | string split "|" | sed -n $argv[2] | string trim
end

function fishfish
    if test (count $argv) -eq 0; or not test "$argv[1]" = --no-greet
        greet
    end
    set -l lines (echo $fish_list | wc -l)
    set -l rand (math "1 + ($(random) % $lines)")
    set_color bryellow
    echo -n "🐟 "
    set_color brgreen
    get_fish $rand 1p
    set_color bryellow
    echo -n "🐟 "
    set_color brcyan
    get_fish $rand 2p
    set_color normal
end

fishfish

complete -c fishfish -f -a --no-greet -d "Skip ASCII greeting"
